### ISSUE TITLE
hello i have problem install gnuworld in FreeBsd

### ISSUE THREAD

**Issue by darksis** [UndernetIRC/gnuworld#1]
Hello i will try install gnuworld in FreeBsd 11 and i get error 
$ make
Making all in libgnuworld
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../include    -I../include -W -Wall -pipe -I../libltdl -I../db -g -O0 -pthread -MT libgnuworld_la-Buffer.lo -MD -MP -MF .deps/libgnuworld_la-Buffer.Tpo -c -o libgnuworld_la-Buffer.lo `test -f 'Buffer.cc' || echo './'`Buffer.cc
libtool: Version mismatch error.  This is libtool 2.4 Debian-2.4-2ubuntu1, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4 Debian-2.4-2ubuntu1
libtool: and run autoconf again.
*** Error code 63

**Comment by hiddn** [comment]
Hi @darksis. It's been a while since you submitted this issue. The way gnuworld compiles has changed since. If you still have troubles, feel free to ask for help on #coder-com channel on the Undernet IRC network (irc.undernet.org).
