### ISSUE TITLE
Support for ircu2's CONFIG_OPERCMDS

### ISSUE THREAD

**Issue by entrope** [UndernetIRC/gnuworld#10]
ircu2's CONFIG_OPERCMDS feature allows server and IRC operators to use some new commands:
 - OPMODE (OM)
 - CLEARMODE (CM)
 - JUPE (JU) for creating or modifying jupes, not just listing them

It looks like gnuworld's current code does not support these:

```
% git grep -i opmode
libircu/msg_M.cc:/* XXX OPMODE FAILS HERE */
```

If GNUworld can correctly handle these, and ideally log them for auditing, that would make it easier for a GNUworld-using network to turn on CONFIG_OPERCMDS.

**Comment by hiddn** [comment]
Resolved.
