### ISSUE TITLE
openchanfix does not properly remove channel modes

### ISSUE THREAD

**Issue by tenye2003** [UndernetIRC/gnuworld#13]
Hello. I have a problem with open.chanfix and I dont know if its a bug or something missconfigured.
Lets say the nick TAKER sets mode +mil 1 and kicks everyone else
When i use /msg c chanfix #test or /msg c requestop #test (tried this too from a op with high points)
* *.myserver.org sets mode -i on #test
* *.myserver.org removes user limit
* *.myserver.org removes channel keyword
* *.myserver.org removes channel operator status from TAKER
* *.myserver.org sets mode +m on #test
* *.myserver.org sets mode +t on #test
* *.myserver.org sets mode +n on #test
* *.myserver.org sets mode +c on #test
But when a user tries to join the channel it says * Cannot join #test (User limit reached). So the modes (i,l,k) are not acctualy properly removed.
clearing channel modes with uworld clearchan command works fine.

Everything else related to C works fine : gathering points , oping opless channels.

**Comment by tenye2003** [comment]
It seems i found the problem on openchanfix.conf.

# Should burst be used to fix takeovers (through a manual fix)?
# Burst guarantees that the abusers will not be reopped due to
# a netsplit, but it can cause problems due to lowering timestamp.
# NOTE: You MUST restart GNUWorld for this change to take place.
useBurstToFix = true

Changed from true to false and it seems it fixed the problem .

**Comment by hiddn** [comment]
I was able to reproduce the problem on the testnet. I've now changed the default value to false for the useBurstToFix config option. Thank you for your report.
