### ISSUE TITLE
C requestop contact wont notify top op to join the channel

### ISSUE THREAD

**Issue by tenye2003** [UndernetIRC/gnuworld#14]
The command /msg c requestop contact wont notifiy the to ops because there is no "if" when type "contact" on the file REQUESTOPCommand.cc 
bool alert = false; and no "if" to change it to alert = true , compared to chanfix contact command (CHANFIXCommand.cc)

On the file CHANFIXCommand.cc
bool alert = false;

if (st.size() > 2) {
  unsigned int pos = 2;
  while(pos < st.size()) {
    if (!strcasecmp(st[pos],"OVERRIDE"))
      override = true;

    if (!strcasecmp(st[pos],"NOW"))
      override = true;

    if (!strcasecmp(st[pos],"YES"))
      override = true;

    if (!strcasecmp(st[pos],"!"))
      override = true;

    if (!strcasecmp(st[pos],"CONTACT"))
      alert = true;

As you see on the last line alert = true if there is "contact" word on the /msg c chanfix #channel contact . This code is missing on REQUESTOPCommand.cc

**Comment by hiddn** [comment]
You're right. I've been saying for over 10 years that CONTACT should be the default. Thanks to your comment, I've now made it so in commit 28dcbbfb492282379aa24c2f38bb4edc93133698
