### ISSUE TITLE
X- The URL can be a maximum of 128 chars! 

### ISSUE THREAD

**Issue by epreom** [UndernetIRC/gnuworld#17]
Hello;

-X- The URL can be a maximum of 128 chars!  
Can we increase the number of characters?

**Comment by empus** [comment]
The URL field is intentionally restricted as it's appended to the DESCRIPTION in channel topics when AUTOTOPIC is enabled.

128 chars is a very long URL for the purpose in which this feature is intended.  A good suggestion would be to use a URL shortening service if required.

**Comment by epreom** [comment]
Thanks
