### ISSUE TITLE
cservice.web.sql

### ISSUE THREAD

**Issue by ZioNeL** [UndernetIRC/gnuworld#7]
Hello,
On table pending_emailchanges, row "phase" is missing. Without this the e-mail change requests via webpage will not work. The link with cookie received on e-mail on phase one is not valid. In order to fix this the following changes must be made:
Change :
CREATE TABLE pending_emailchanges (
	cookie VARCHAR(128) NOT NULL,
	user_id INT4 NOT NULL,
	old_email VARCHAR(255) NOT NULL,
	new_email VARCHAR(255) NOT NULL,
	expiration INT4 NOT NULL
);

TO:
CREATE TABLE pending_emailchanges (
	cookie VARCHAR(128) NOT NULL,
	user_id INT4 NOT NULL,
	old_email VARCHAR(255) NOT NULL,
	new_email VARCHAR(255) NOT NULL,
	expiration INT4 NOT NULL,
       phase INT4 NOT NULL
);

**Comment by tenye2003** [comment]
Yep. You're right this fixed the email change problem.

**Comment by hiddn** [comment]
I usually don't deal with mod.cservice, but this is clearly an issue. Thank you for submitting it.

I see you reported this a long time ago, so we were very slow to react. If you feel that you need to get our attention, don't hesitate to report it in #coder-com on the Undernet IRC network.

Thanks again.

Hidden
