### ISSUE TITLE
Admin password in cservice.addme.sql

### ISSUE THREAD

**Issue by ZioNeL** [UndernetIRC/gnuworld#8]
Please update the password for admin account creation on cservice.addme.sql to a more complex one.
With actual password "temPass" logins on webpage are not possible due to error "Too many redirects." .

This fix was suggested by Ratler to set a complex one ( temPass2020@ ) .
Here is the encrypted pass: xEDi1V791f7bddc526de7e3b0602d0b2993ce21d 

All the best and keep up the good work.

**Comment by tenye2003** [comment]
Can confirm that works !
